#!/bin/bash

alias mosh='PERL5LIB="" mosh'
alias ssh-adds='ssh-add ~/.ssh/id_rsa; ssh-add ~/.ssh/id_rsa.recollect'
alias screen='screen -U' # force unicode screens
alias nopaste='nopaste -x'
alias ale='ssh recollect@ale -t screen -x'
alias staging='ssh recollect@staging -t screen -x'
alias cdr='cd ~/src/recollect'
alias cdi='cd ~/src/integrations'
alias b='ssh -t boil -- screen -x'
alias c='ssh cellar -t screen -x'

alias agu='sudo apt-get update'
alias agdu='sudo apt-get update; sudo apt-get dist-upgrade'
alias agi='sudo apt-get update; sudo apt-get install'
alias acs='apt-cache search'
alias acsh='apt-cache show'

ls --version > /dev/null 2>&1 && alias ll='ls -l --classify --color=auto'
echo x | (grep x --color >/dev/null 2>&1) && alias grep='grep --color=auto'

alias kevin='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u kevinj'
alias luke='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u lukec'
alias leigh='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u leigh'
alias wataru='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u wataru'
alias brandon='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u brandon'
alias dev='~/src/recollect/dev-bin/mosh-dev lukec'
alias pan='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u pan'
alias candace='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u candace'
alias viz='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u viswanathms'
alias therese='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u therese'
alias jason='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u json'
alias test='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u test'
alias intern='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u intern'
alias ci='ssh jenkins sudo -u jenkins /var/lib/jenkins/jobs/recollect/workspace/dev-bin/jenkins/build/run-ci'
alias courtney='ssh -p 48022 boil.recollect.net -t sudo /opt/recollect/bin/docker-dev -u courtneyportnoy'

alias backend-1.prod='ssh -t njv-backend-1.prod sudo -H -u recollect tmuxinator start recollect'
alias backend-1.staging='ssh -t tpx-backend-1.staging sudo -H -u recollect tmuxinator start recollect'
alias backend-2.prod='ssh -t njv-backend-2.prod sudo -H -u recollect tmuxinator start recollect'
alias backend-2.staging='ssh -t tpx-backend-2.staging sudo -H -u recollect tmuxinator start recollect'

alias jobs-1.prod='ssh -t njv-jobs-1.prod sudo -H -u recollect tmuxinator start recollect'
alias jobs-2.prod='ssh -t njv-jobs-2.prod sudo -H -u recollect tmuxinator start recollect'
#alias jobs-1.staging='ssh -t jobs-1.staging sudo -H -u recollect tmuxinator start recollect'
#alias jobs-2.staging='ssh -t jobs-2.staging sudo -H -u recollect tmuxinator start recollect'

alias boil='ssh -p 48022 boil.recollect.net'

alias heaven='ssh -R 3179:localhost:3179 heaven'
