export LANG="en_US.UTF-8"  
export EDITOR=vim          
export PAGER=less          
export HISTIGNORE="&:[bf]g:exit"
export PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
export PATH="./bin:$HOME/bin:/opt/local/bin:/usr/local/Cellar/go/1.2/libexec/bin:$PATH"
export GOPATH="$HOME/.go:$HOME"
export PATH="$PATH:/usr/local/opt/go/libexec/bin:$GOPATH/bin"
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
export PATH="~/src/camlistore/bin:$PATH"

set -o vi
umask 022                  

if [ -n "$TTY" ]; then     
    stty -ixon # get rid of ^S and ^Q
fi

alias profile='source ~/.bashrc'
alias ll='ls -l'
alias screen='TERM=screen screen'
alias pmf='perl Makefile.PL < /dev/null'
alias mt='make test'

if [ "$TERM" = "screen" ]; then
  swtcwd () {
    local HPWD="$PWD"
    case $HPWD in
      $HOME) HPWD="~";;
      $HOME/*) HPWD=`echo $PWD | perl -pe 's!.*/!!'`;;
    esac
    printf '\ek%s\e\\' "$HPWD"
  }
  PROMPT_COMMAND="swtcwd; $PROMPT_COMMAND"
fi

##############
# GIT Section
##############             
alias gst='git status'     
alias gbr='git branch'
alias gd='git diff'
alias gdc='git diff --cached'
alias ga='git add'
alias gco='git checkout'
alias gci='git commit -v'
alias gcim='git commit -v -m'
alias gcia='git commit -v -a'
alias gciam='git commit -v -a -m'
alias gl='git log'
alias glol='git log --pretty=oneline'
alias gup='git pull --rebase'
alias gpu='git push'
alias guppy='gup && gpu'
alias sup='git stash && gup && git stash pop'
alias suppy='git stash && gup && gpu && git stash pop'
alias gcp='git cherry-pick -x'
alias gundo='git reset HEAD^'

. $HOME/.aliases-lukec

export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/lukec/.boot2docker/certs/boot2docker-vm

source /Users/lukec/.gvm/scripts/gvm

alias d='docker'
alias weather='curl http://wttr.in/Vancouver'
alias staging='tmuxinator start staging'
alias prod='tmuxinator start prod'
