export LANG="en_US.UTF-8"  
export EDITOR=vim          
export PAGER=less          
export HISTIGNORE="&:[bf]g:exit"
export PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
export PATH="$HOME/.plenv/shims:./bin:$HOME/bin:/opt/local/bin:/usr/local/Cellar/go/1.2/libexec/bin:~/Library/Python/3.6/bin:$PATH"
export GOPATH="$HOME"
export PATH="$PATH:/usr/local/opt/go/libexec/bin:$GOPATH/bin"
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
export PATH="/Users/lukec/Library/Python/3.7/bin:$PATH"
export REC="~/src/recollect"
export PATH="$REC/bin:$REC/bin/scripts:$REC/bin/ops:$REC/dev-bin:$PATH"
export PERL5LIB="$REC/lib"

set -o vi
umask 022                  

if [ -n "$TTY" ]; then     
    stty -ixon # get rid of ^S and ^Q
fi

alias profile='source ~/.bashrc'
alias ll='ls -l'
alias screen='TERM=screen screen'
alias pmf='perl Makefile.PL < /dev/null'
alias mt='make test'

if [ "$TERM" = "screen" ]; then
  swtcwd () {
    local HPWD="$PWD"
    case $HPWD in
      $HOME) HPWD="~";;
      $HOME/*) HPWD=`echo $PWD | perl -pe 's!.*/!!'`;;
    esac
    printf '\ek%s\e\\' "$HPWD"
  }
  PROMPT_COMMAND="swtcwd; $PROMPT_COMMAND"
fi

##############
# GIT Section
##############             
alias gst='git status'     
alias gbr='git branch'
alias gd='git diff'
alias gdc='git diff --cached'
alias ga='git add'
alias gco='git checkout'
alias gci='git commit -v'
alias gcim='git commit -v -m'
alias gcia='git commit -v -a'
alias gciam='git commit -v -a -m'
alias gl='git log'
alias glol='git log --pretty=oneline'
alias gup='git pull --rebase'
alias gpu='git push'
alias guppy='gup && gpu'
alias sup='git stash && gup && git stash pop'
alias suppy='git stash && gup && gpu && git stash pop'
alias gcp='git cherry-pick -x'
alias gundo='git reset HEAD^'

. $HOME/.aliases-lukec

# export DOCKER_TLS_VERIFY=1
# export DOCKER_HOST=tcp://192.168.59.103:2376
# export DOCKER_CERT_PATH=/Users/lukec/.boot2docker/certs/boot2docker-vm

# source /Users/lukec/.gvm/scripts/gvm

alias d='docker'
alias dc='docker-compose'
alias weather='curl http://wttr.in/Vancouver'
alias staging='tmuxinator start staging'
alias prod='tmuxinator start prod'
alias ci-tmux='ssh -t ci sudo -H -u recollect tmuxinator start recollect'

export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[ -f /Users/lukec/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash ] && . /Users/lukec/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[ -f /Users/lukec/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash ] && . /Users/lukec/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[ -f /Users/lukec/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.bash ] && . /Users/lukec/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.bash